on:
  schedule:
    # The following is counter intuitive.
    # As the name suggests, the workflow is designed to run daily.
    # However, the workflow itself is idempotent, so it's safe to run it more often.
    # I would prefer that the workflow runs once an hour, and by virtue of its
    # idempotency, only create one new daily note, than run exactly once a day
    # and possibly fail to generate the daily note.
    #- cron: '0 * * * *' # every hour
    - cron: '*/5 * * * *' # every hour

jobs:
  daily-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Metadata
        id: metadata
        run: |
          path_year="$(date +%Y)"
          path_month="$path_year/$(date +%B)"
          path_full="$path_month/$(date +%d).md"
          title="$(date +%A), $(date +%B) $(date +%d), $(date +%Y)"

          echo path_year=$path_year>> $GITHUB_OUTPUT
          echo path_month=$path_month>> $GITHUB_OUTPUT
          echo path_full=$path_full >> $GITHUB_OUTPUT
          echo title=$title >> $GITHUB_OUTPUT
          
      - name: Create Daily Note File (${{ steps.metadata.outputs.title }})
        env:
          PATH_YEAR: ${{ steps.metadata.outputs.path_year }}
          PATH_MONTH: ${{ steps.metadata.outputs.path_month }}
          PATH_FULL: ${{ steps.metadata.outputs.path_full }}
          TITLE: ${{ steps.metadata.outputs.title }}
        run: |
          if [[ $(date +%A) == "Saturday" ]]; then
            SHABBAT=$(cat << EOF
          ### $(curl https://www.hebcal.com/hebcal\?v\=1\&cfg\=json\&s\=on\&year\=now\&start\=$(date +%Y)-$(date +%m)-$(date +%d)\&end\=$(date +%Y)-$(date +%m)-$(date +%d)\&geo\=none\&s\=on | jq -r '.items[].title')
          :candle: :candle: :bread: :bread: :wine_glass:
          EOF
            )
          fi

          EMPTY_NOTE=$(cat << EOF
          # $TITLE
          ![banner](https://picsum.photos/seed/$(date +%Y)-$(date +%B)-$(date +%d)/500/200)
          > _"$(curl https://zenquotes.io/api/today | jq -r '.[].q')"_
          <!-- START doctoc -->
          <!-- END doctoc -->
          ## Notes
          $SHABBAT
          <!--- TODO: fill me out, if you have time today --->
          EOF
          )

          # Create parent dir for the daily note, if it doesn't exist
          mkdir -p $(dirname $PATH_FULL)

          if [[ ! -f $PATH_FULL ]]; then
            echo "Creating empty daily note: $PATH_FULL"
            echo "$EMPTY_NOTE" > $PATH_FULL
          else 
            echo "Daily note already exists: $PATH_FULL"
          fi

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Adding daily note for ${{ steps.metadata.outputs.title }}'
          add: '*.md'

  update-tocs:
    needs: daily-note
    runs-on: ubuntu-latest
    steps:
      - name: Update TOCs
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TARGET_PATHS: '.'
          MAX_HEADER_LEVEL: 6
          CHECK_ONLY_DEFAULT_BRANCH: true