on:
  push:
    branches:
      - main

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Update TOCs
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TARGET_PATHS: '*.md'