on:
  push:
    branches:
      - main

jobs:
  update-tocs:
    runs-on: ubuntu-latest
    steps:
      - name: Update TOCs
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TARGET_PATHS: '.'
          MAX_HEADER_LEVEL: 6
          CHECK_ONLY_DEFAULT_BRANCH: true